import { Router,type Request } from "express";import { z } from "zod";
import type { Environment } from "../../config/env";import { authenticate } from "../../middleware/authenticate";import { requirePermission } from "../../middleware/authorize";import { requirePasswordChanged } from "../../middleware/require-password-changed";import { validateBody } from "../../middleware/validate";import { AppError } from "../../shared/errors/app-error";import { asyncHandler } from "../../shared/http/async-handler";import type { AuthStore } from "../auth/auth.repository";import type { RequestMetadata } from "../audit/audit.repository";import { diagnosticCancelSchema,diagnosticOrderSchema,diagnosticOrderUpdateSchema,diagnosticResultSchema,diagnosticWorklistQuerySchema } from "./diagnostic.schemas";import { DiagnosticService } from "./diagnostic.service";
export function createDiagnosticRouter(s:DiagnosticService,a:AuthStore,e:Environment){const r=Router();r.use(authenticate(a,e.SESSION_COOKIE_NAME,e.SESSION_IDLE_MINUTES),requirePasswordChanged);
 r.post("/orders",requirePermission("diagnostic.order"),validateBody(diagnosticOrderSchema),asyncHandler(async(q,p)=>p.status(201).json({item:await s.create(q.auth!.userId,q.body,meta(q))})));
 r.get("/orders",requirePermission("diagnostic.worklist"),asyncHandler(async(q,p)=>{const x=diagnosticWorklistQuerySchema.safeParse(q.query);if(!x.success)throw new AppError(400,"VALIDATION_ERROR","Invalid diagnostic query",x.error.flatten());p.json({items:await s.list(x.data.status,x.data.limit,x.data.includeReviewed??true)});}));
 r.get("/orders/:id",requirePermission("diagnostic.worklist"),asyncHandler(async(q,p)=>{const item=await s.getById(uuid(q.params.id));if(!item)throw new AppError(404,"DIAGNOSTIC_ORDER_NOT_FOUND","Diagnostic order was not found");p.json({item});}));
 r.post("/orders/:id/start",requirePermission("diagnostic.worklist"),asyncHandler(async(q,p)=>p.json({item:await s.start(uuid(q.params.id),q.auth!.userId,meta(q))})));
 r.put("/items/:id/result",requirePermission("diagnostic.result.enter"),validateBody(diagnosticResultSchema),asyncHandler(async(q,p)=>p.json({item:await s.enterResult(uuid(q.params.id),q.body,q.auth!.userId,meta(q))})));
 r.post("/items/:id/verify",requirePermission("diagnostic.result.verify"),asyncHandler(async(q,p)=>p.json({item:await s.verify(uuid(q.params.id),q.auth!.userId,meta(q))})));
 r.post("/orders/:id/review",requirePermission("diagnostic.order"),asyncHandler(async(q,p)=>p.json({item:await s.review(uuid(q.params.id),q.auth!.userId,meta(q))})));
 r.patch("/orders/:id",requirePermission("diagnostic.order"),validateBody(diagnosticOrderUpdateSchema),asyncHandler(async(q,p)=>p.json({item:await s.updateOrder(uuid(q.params.id),q.body,q.auth!.userId,meta(q))})));
 r.post("/orders/:id/cancel",requirePermission("diagnostic.order"),validateBody(diagnosticCancelSchema),asyncHandler(async(q,p)=>p.json({item:await s.cancelOrder(uuid(q.params.id),q.body.reason,q.auth!.userId,meta(q))})));
 r.post("/items/:id/cancel",requirePermission("diagnostic.order"),validateBody(diagnosticCancelSchema),asyncHandler(async(q,p)=>p.json({item:await s.cancelItem(uuid(q.params.id),q.body.reason,q.auth!.userId,meta(q))})));
 return r;}
function uuid(v:unknown){return z.string().uuid().parse(v);}function meta(q:Request):RequestMetadata{return{requestId:q.requestId,ipAddress:q.ip,userAgent:q.get("user-agent")};}
