import type{Pool,PoolClient}from"pg";import{withTransaction}from"../../database/transaction";import type{Queryable}from"../../database/types";import{AppError}from"../../shared/errors/app-error";import type{AuditEventInput}from"../audit/audit.repository";import{AuditRepository}from"../audit/audit.repository";
export type Invoice={id:string;invoice_number:string;visit_id:string;patient_id:string;visit_number:string;patient_name:string;status:string;subtotal:string;discount_amount:string;total:string;amount_paid:string;balance_due:string;discount_reason:string|null;issued_at:Date;paid_at:Date|null;lines:Array<Record<string,unknown>>;payments:Array<Record<string,unknown>>};
const SELECT_INVOICE=`select i.id,i.invoice_number,i.visit_id,i.patient_id,v.visit_number,concat_ws(' ',p.first_name,p.middle_name,p.last_name) patient_name,i.status,i.subtotal::text,i.discount_amount::text,i.total::text,i.amount_paid::text,(i.total-i.amount_paid)::text balance_due,i.discount_reason,i.issued_at,i.paid_at,
 coalesce((select jsonb_agg(jsonb_build_object('id',l.id,'catalog_item_id',l.catalog_item_id,'line_type',l.line_type,'description',l.description,'quantity',l.quantity,'unit_price',l.unit_price,'line_total',l.line_total)order by l.created_at,l.id)from clinic.invoice_lines l where l.invoice_id=i.id),'[]'::jsonb)lines,
 coalesce((select jsonb_agg(jsonb_build_object('id',x.id,'receipt_number',x.receipt_number,'amount',x.amount,'method',x.method,'reference',x.reference,'status',x.status,'paid_at',x.paid_at)order by x.paid_at,x.id)from clinic.payments x where x.invoice_id=i.id),'[]'::jsonb)payments
 from clinic.invoices i join clinic.visits v on v.id=i.visit_id join clinic.patients p on p.id=i.patient_id`;
export class BillingRepository{constructor(private readonly pool:Pool,private readonly audit:AuditRepository){}
 async issue(input:{visitId:string;discountAmount:number;discountReason?:string;items:Array<{catalogItemId:string;quantity:number;description?:string}>},actor:string,discountApproved:boolean,event:AuditEventInput):Promise<Invoice>{return withTransaction(this.pool,async c=>{
  const vr=await c.query<{patient_id:string;status:string}>("select patient_id,status from clinic.visits where id=$1 for update",[input.visitId]);const v=vr.rows[0];if(!v)throw new AppError(404,"VISIT_NOT_FOUND","Visit was not found");if(["cancelled","completed","billed"].includes(v.status))throw new AppError(409,"VISIT_NOT_BILLABLE","Visit cannot be invoiced");if(input.discountAmount>0&&!discountApproved)throw new AppError(403,"DISCOUNT_APPROVAL_REQUIRED","You do not have permission to approve discounts");
  const catalog=await c.query<{id:string;item_type:string;name:string;price:string}>("select id,item_type,name,price::text from clinic.catalog_items where id=any($1::uuid[]) and active=true order by id",[input.items.map(x=>x.catalogItemId)]);const map=new Map(catalog.rows.map(x=>[x.id,x]));if(map.size!==new Set(input.items.map(x=>x.catalogItemId)).size)throw new AppError(400,"CATALOG_ITEM_INVALID","One or more invoice items are invalid");
  const ir=await c.query<{id:string}>(`insert into clinic.invoices(visit_id,patient_id,status,subtotal,discount_amount,total,discount_reason,discount_approved_by,issued_by)
   values($1,$2,'issued',0,$3::numeric,(0::numeric-$3::numeric),$4,$5,$6) returning id`,[input.visitId,v.patient_id,input.discountAmount,input.discountReason??null,input.discountAmount>0?actor:null,actor]);const id=ir.rows[0]!.id;
  for(const x of input.items){const item=map.get(x.catalogItemId);if(!item)throw new AppError(400,"CATALOG_ITEM_INVALID","Invoice item is invalid");await c.query(`insert into clinic.invoice_lines(invoice_id,catalog_item_id,line_type,description,quantity,unit_price,line_total)
   values($1,$2,$3,$4,$5::numeric,$6::numeric,round($5::numeric*$6::numeric,2))`,[id,item.id,item.item_type,x.description??item.name,x.quantity,item.price]);}
  const totals=await c.query<{subtotal:string}>("select coalesce(sum(line_total),0)::text subtotal from clinic.invoice_lines where invoice_id=$1",[id]);const subtotal=Number(totals.rows[0]!.subtotal);if(input.discountAmount>subtotal)throw new AppError(400,"DISCOUNT_EXCEEDS_SUBTOTAL","Discount cannot exceed invoice subtotal");const total=subtotal-input.discountAmount;
  await c.query("update clinic.invoices set subtotal=$2::numeric,total=$3::numeric,status=case when $3::numeric=0 then 'paid' else 'issued' end,paid_at=case when $3::numeric=0 then now() else null end,updated_at=now() where id=$1",[id,subtotal,total]);
  await c.query("update clinic.visits set status='ready_for_billing',updated_at=now() where id=$1",[input.visitId]);if(total===0)await releaseAfterPayment(c,input.visitId,actor);
  const invoice=(await this.find(id,c))!;await this.audit.record({...event,resourceId:id,afterData:invoice},c);return invoice;
 });}
 async outstanding(limit:number){const r=await this.pool.query<Invoice>(`${SELECT_INVOICE} where i.status in('issued','partially_paid') order by i.issued_at,i.id limit $1`,[limit]);return r.rows;}
 async paidToday(limit:number){const r=await this.pool.query<Invoice>(`${SELECT_INVOICE} where i.status='paid' and i.paid_at>=current_date order by i.paid_at desc,i.id limit $1`,[limit]);return r.rows;}
 async byVisit(visitId:string){const r=await this.pool.query<Invoice>(`${SELECT_INVOICE} where i.visit_id=$1`,[visitId]);return r.rows[0]??null;}
 async pay(invoiceId:string,input:{amount:number;method:string;reference?:string},actor:string,event:AuditEventInput){return withTransaction(this.pool,async c=>{
  const locked=await c.query<{visit_id:string;status:string;total:string;amount_paid:string}>("select visit_id,status,total::text,amount_paid::text from clinic.invoices where id=$1 for update",[invoiceId]);const i=locked.rows[0];if(!i)throw new AppError(404,"INVOICE_NOT_FOUND","Invoice was not found");if(!["issued","partially_paid"].includes(i.status))throw new AppError(409,"INVOICE_NOT_PAYABLE","Invoice is not open for payment");const balance=Number(i.total)-Number(i.amount_paid);if(input.amount>balance)throw new AppError(409,"PAYMENT_EXCEEDS_BALANCE","Payment exceeds the outstanding balance");
  const pr=await c.query<{id:string;receipt_number:string}>("insert into clinic.payments(invoice_id,amount,method,reference,collected_by)values($1,$2::numeric,$3,$4,$5)returning id,receipt_number",[invoiceId,input.amount,input.method,input.reference??null,actor]);const next=Number(i.amount_paid)+input.amount;const paid=Math.abs(next-Number(i.total))<0.001;await c.query("update clinic.invoices set amount_paid=$2::numeric,status=$3,paid_at=case when $3='paid' then now() else null end,updated_at=now() where id=$1",[invoiceId,next,paid?"paid":"partially_paid"]);if(paid)await releaseAfterPayment(c,i.visit_id,actor);const invoice=(await this.find(invoiceId,c))!;await this.audit.record({...event,resourceId:pr.rows[0]!.id,afterData:{receiptNumber:pr.rows[0]!.receipt_number,invoice}},c);return invoice;
 });}
 private async find(id:string,db:Queryable){const r=await db.query<Invoice>(`${SELECT_INVOICE} where i.id=$1`,[id]);return r.rows[0]??null;}
}
async function releaseAfterPayment(c:PoolClient,visitId:string,actor:string){const rx=await c.query("update clinic.prescriptions set status='payment_approved',updated_at=now() where visit_id=$1 and status='awaiting_payment' returning id",[visitId]);if(rx.rowCount){await c.query("update clinic.visits set status='medication_prescribed',updated_at=now() where id=$1",[visitId]);const active=await c.query("select 1 from clinic.queue_entries where visit_id=$1 and status in('waiting','called','in_service')",[visitId]);if(!active.rowCount){const q=await c.query<{id:string}>("insert into clinic.queue_entries(visit_id,station,priority)select id,'pharmacy',priority from clinic.visits where id=$1 returning id",[visitId]);await c.query("insert into clinic.queue_events(queue_entry_id,from_status,to_status,actor_user_id,notes)values($1,null,'waiting',$2,'Invoice paid')",[q.rows[0]!.id,actor]);}}else await c.query("update clinic.visits set status='billed',completed_at=now(),updated_at=now() where id=$1",[visitId]);}
